export type Appliance = {
  id: string;
  name: string;
  watts: number;
};

/** 80 household / commercial devices — single source of truth for the calculator catalog. */
export const APPLIANCES: Appliance[] = [
  { id: "fridge-standard", name: "Standart Buzdolabı", watts: 150 },
  { id: "washing-machine", name: "Çamaşır Makinesi", watts: 2000 },
  { id: "vacuum", name: "Elektrikli Süpürge", watts: 2000 },
  { id: "dishwasher", name: "Bulaşık Makinesi", watts: 1800 },
  { id: "tv-55-led", name: '55" LED TV', watts: 130 },
  {
    id: "ac-12000-btu",
    name: "Klima (Sıcak/Soğuk 12.000 BTU)",
    watts: 1200,
  },
  { id: "microwave", name: "Mikrodalga Fırın", watts: 1200 },
  { id: "kettle", name: "Elektrikli Su Isıtıcı (Kettle)", watts: 2000 },
  { id: "router-modem", name: "Router / Modem", watts: 15 },
  { id: "led-bulb-9w", name: "LED Ampul (9W)", watts: 9 },
  { id: "tv-82-led", name: '82" LED TV', watts: 260 },
  { id: "tv-75-led", name: '75" LED TV', watts: 220 },
  { id: "tv-65-led", name: '65" LED TV', watts: 180 },
  { id: "tv-43-led", name: '43" LED TV', watts: 90 },
  { id: "tv-32-led", name: '32" LED TV', watts: 55 },
  {
    id: "fridge-freezer-combo",
    name: "Derin Donduruculu Buzdolabı",
    watts: 400,
  },
  { id: "fridge-double-door", name: "Çift Kapılı Buzdolabı", watts: 350 },
  { id: "fridge-mini", name: "Mini Buzdolabı", watts: 80 },
  { id: "ac-18000-btu", name: "Klima (18.000 BTU)", watts: 1800 },
  { id: "ac-24000-btu", name: "Klima (24.000 BTU)", watts: 2400 },
  {
    id: "ac-9000-cool",
    name: "Klima (Sadece Soğutma 9.000 BTU)",
    watts: 900,
  },
  {
    id: "dryer",
    name: "Çamaşır Kurutma Makinesi",
    watts: 3000,
  },
  { id: "electric-oven", name: "Elektrikli Fırın", watts: 2500 },
  { id: "cooktop-induction", name: "Ocak (İndüksiyon)", watts: 3500 },
  { id: "cooktop-electric", name: "Ocak (Elektrikli)", watts: 2000 },
  { id: "toaster", name: "Tost Makinesi", watts: 1000 },
  { id: "coffee-maker", name: "Kahve Makinesi", watts: 1500 },
  { id: "blender", name: "Blender", watts: 500 },
  { id: "robot-vacuum", name: "Robot Süpürge", watts: 30 },
  { id: "air-purifier", name: "Hava Temizleyici", watts: 50 },
  { id: "fan", name: "Vantilatör", watts: 60 },
  { id: "ceiling-fan", name: "Tavan Vantilatörü", watts: 75 },
  {
    id: "heater-radiator",
    name: "Elektrikli Isıtıcı (Radyatör)",
    watts: 2000,
  },
  {
    id: "heater-fan",
    name: "Elektrikli Isıtıcı (Fan Tipi)",
    watts: 1500,
  },
  {
    id: "water-heater-combi",
    name: "Su Isıtıcı (Kombi - Elektrik)",
    watts: 2000,
  },
  { id: "pump-home", name: "Su Pompası (Ev Tipi)", watts: 500 },
  { id: "pump-farm", name: "Su Pompası (Tarım)", watts: 3000 },
  { id: "well-pump", name: "Kuyu Pompası", watts: 750 },
  { id: "laptop", name: "Laptop", watts: 65 },
  { id: "desktop", name: "Masaüstü Bilgisayar", watts: 300 },
  { id: "monitor", name: "Monitör", watts: 30 },
  { id: "printer", name: "Yazıcı", watts: 200 },
  { id: "phone-charger", name: "Akıllı Telefon Şarjı", watts: 20 },
  { id: "tablet-charger", name: "Tablet Şarjı", watts: 15 },
  { id: "game-console", name: "Oyun Konsolu", watts: 200 },
  { id: "projector", name: "Projeksiyon", watts: 350 },
  { id: "led-bulb-15w", name: "LED Ampul (15W)", watts: 15 },
  { id: "bulb-fluorescent", name: "Floresan Ampul", watts: 25 },
  { id: "bulb-halogen", name: "Halojen Ampul", watts: 100 },
  { id: "spot-led", name: "Spot LED", watts: 5 },
  { id: "garden-lights", name: "Bahçe Aydınlatması", watts: 50 },
  {
    id: "ev-charge-slow",
    name: "Elektrikli Araç Şarjı (Yavaş)",
    watts: 3700,
  },
  {
    id: "ev-charge-fast",
    name: "Elektrikli Araç Şarjı (Hızlı)",
    watts: 11000,
  },
  { id: "cctv-dvr", name: "Güvenlik Kamerası (DVR)", watts: 30 },
  { id: "alarm", name: "Alarm Sistemi", watts: 15 },
  { id: "doorbell-video", name: "Kapı Zili (Video)", watts: 10 },
  { id: "sat-receiver", name: "Uydu Yayın Alıcısı", watts: 25 },
  { id: "stereo", name: "Müzik Sistemi / Hoparlör", watts: 150 },
  { id: "home-theater", name: "Ev Sinema Sistemi", watts: 400 },
  {
    id: "garage-door",
    name: "Elektrikli Kapı / Garaj Motoru",
    watts: 300,
  },
  { id: "elevator-small", name: "Asansör (Küçük)", watts: 2500 },
  {
    id: "ac-cassette-commercial",
    name: "Kasa Tipi Klima (Ticari)",
    watts: 5000,
  },
  {
    id: "hvac-central",
    name: "Merkezi Klima Sistemi",
    watts: 8000,
  },
  { id: "industrial-fan", name: "Endüstriyel Fan", watts: 2200 },
  { id: "pos", name: "Yazarkasa / POS", watts: 40 },
  { id: "cooler-display", name: "Soğutuculu Vitrin", watts: 800 },
  { id: "freezer-display", name: "Donduruculu Vitrin", watts: 1200 },
  {
    id: "gozleme-grill",
    name: "Elektrikli Gözleme Tavası",
    watts: 2500,
  },
  { id: "fryer", name: "Fritöz (Elektrikli)", watts: 2000 },
  { id: "bread-oven-small", name: "Ekmek Fırını (Küçük)", watts: 3000 },
  {
    id: "coffee-commercial",
    name: "Kahve Makinesi (Ticari)",
    watts: 3000,
  },
  { id: "tea-urn", name: "Çay Kazanı", watts: 2500 },
  { id: "water-dispenser", name: "Su Dispenseri", watts: 100 },
  {
    id: "irrigation-pump",
    name: "Sulama Sistemi Pompası",
    watts: 1500,
  },
  { id: "greenhouse-heat", name: "Sera Isıtma", watts: 5000 },
  { id: "electric-fence", name: "Elektrikli Çit", watts: 50 },
  {
    id: "chicken-coop-heat",
    name: "Tavuk Kümesi Isıtma",
    watts: 1000,
  },
  { id: "milk-tank", name: "Süt Soğutma Tankı", watts: 1500 },
  {
    id: "washing-auto",
    name: "Tam Otomatik Çamaşır Makinesi",
    watts: 2500,
  },
  {
    id: "solar-charge-controller",
    name: "Güneş Paneli Şarj Regülatörü",
    watts: 20,
  },
];

export function getApplianceById(id: string): Appliance | undefined {
  return APPLIANCES.find((a) => a.id === id);
}
